"""
RFM (Recency, Frequency, Monetary) calculation.

Recency  = days between the analysis date and the customer's most recent purchase.
Frequency = number of unique invoices (orders) placed by the customer.
Monetary  = total revenue (Quantity x UnitPrice) generated by the customer.

The analysis date defaults to (max invoice date in the data) + 1 day, which
avoids using any "future" information relative to the dataset itself.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

import pandas as pd

from src.data_loader import CUSTOMER_ID, INVOICE_DATE, INVOICE_NO
from src.preprocessing import REVENUE


def get_default_analysis_date(df: pd.DataFrame) -> pd.Timestamp:
    """Analysis date = one day after the most recent transaction in the data."""
    return df[INVOICE_DATE].max() + pd.Timedelta(days=1)


def compute_rfm(
    df: pd.DataFrame, analysis_date: Optional[pd.Timestamp] = None
) -> pd.DataFrame:
    """
    Compute per-customer RFM metrics from cleaned transaction-level data.

    Args:
        df: cleaned transactions DataFrame (output of preprocessing.clean_transactions).
        analysis_date: reference date for Recency. Defaults to max(date) + 1 day.

    Returns:
        DataFrame indexed by customer_id with columns:
            recency, frequency, monetary, last_purchase_date, first_purchase_date,
            total_line_items
    """
    if analysis_date is None:
        analysis_date = get_default_analysis_date(df)

    grouped = df.groupby(CUSTOMER_ID)
    rfm = grouped.agg(
        last_purchase_date=(INVOICE_DATE, "max"),
        first_purchase_date=(INVOICE_DATE, "min"),
        frequency=(INVOICE_NO, "nunique"),
        monetary=(REVENUE, "sum"),
        total_line_items=(INVOICE_NO, "count"),
    )
    rfm["recency"] = (analysis_date - rfm["last_purchase_date"]).dt.days
    rfm = rfm[
        [
            "recency",
            "frequency",
            "monetary",
            "last_purchase_date",
            "first_purchase_date",
            "total_line_items",
        ]
    ]
    return rfm.reset_index()


def analysis_date_display(analysis_date: pd.Timestamp) -> str:
    """Human-friendly string for showing the analysis date in the UI."""
    if isinstance(analysis_date, (pd.Timestamp, datetime)):
        return analysis_date.strftime("%Y-%m-%d")
    return str(analysis_date)
